apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-security-service
  labels:
    app: faculty-security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty-security-service
  template:
    metadata:
      labels:
        app: faculty-security-service
    spec:
      containers:
        - name: faculty-security-service
          image: faculty_management-faculty-security-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: DISCOVERY_SERVICE_URL
              value: "http://faculty-discovery-service:8761/eureka"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-security-service
spec:
  type: LoadBalancer
  selector:
    app: faculty-security-service
  ports:
    - port: 9090
      targetPort: 9090